# Generated by Django 4.2.11 on 2024-03-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.DateField()),
                ('death_year', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('bookshelf_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('download_count', models.IntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500, null=True, verbose_name='link of book')),
                ('author', models.ManyToManyField(to='backend_app.author')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.bookshelf')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.genre')),
            ],
        ),
    ]
