# Generated by Django 4.2.11 on 2024-03-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'books_author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('media_type', models.CharField(max_length=16)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'books_book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksBookAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksauthor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksbook')),
            ],
            options={
                'db_table': 'books_book_authors',
                'managed': True,
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.CreateModel(
            name='BooksBookBookshelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksbook')),
            ],
            options={
                'db_table': 'books_book_bookshelves',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksBookLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksbook')),
            ],
            options={
                'db_table': 'books_book_languages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksBookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'books_bookshelf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksBookSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksbook')),
            ],
            options={
                'db_table': 'books_book_subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=256)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksbook')),
            ],
            options={
                'db_table': 'books_format',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'books_language',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'books_subject',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookshelf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Bookshelf',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='booksbooksubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.bookssubject'),
        ),
        migrations.AddField(
            model_name='booksbooklanguages',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.bookslanguage'),
        ),
        migrations.AddField(
            model_name='booksbookbookshelves',
            name='bookshelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.booksbookshelf'),
        ),
        migrations.AlterUniqueTogether(
            name='booksbooksubjects',
            unique_together={('book', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='booksbooklanguages',
            unique_together={('book', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='booksbookbookshelves',
            unique_together={('book', 'bookshelf')},
        ),
    ]
