# Generated by Django 4.2.11 on 2024-03-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_booksauthor_booksbook_booksbookauthors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksformat',
            name='book',
        ),
        migrations.AddField(
            model_name='booksbook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.booksauthor'),
        ),
        migrations.AddField(
            model_name='booksbook',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.booksformat'),
        ),
    ]
