# Generated by Django 4.2.11 on 2024-03-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_remove_booksformat_book_booksbook_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksbook',
            options={'managed': True, 'ordering': ['-download_count']},
        ),
        migrations.AddField(
            model_name='booksbook',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.bookslanguage'),
        ),
    ]
